Lab4
MaSaHaKa229/IU5-Frontend-2022 pull request #3
Opened 2022-03-15 18:40 UTC by MaSaHaKa229

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Убедись, что поднялся vercel с твоей работой и бот написал тебе коментарий в пре со ссылкой.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ master
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, мы поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь зеленую галочку от нас на пре, можешь смержить PR.

- [ ] Ты увидел зеленую галочку от нас на пре?

2022-03-21 17:27 UTC, antoffee requested changes
почему тут третья лаба, оставь в ПРе только 4

2022-03-21 17:38 UTC, MaSaHaKa229 commented
> почему тут третья лаба, оставь в ПРе только 4

Не понял. Файлы с 3 лабой должны быть пустые?
Мы же после копии из мастера будем получать коды из предыдущих лаб. А так убрал код 3 лабы

2022-03-23 09:30 UTC, antoffee commented
> > почему тут третья лаба, оставь в ПРе только 4
> 
> Не понял. Файлы с 3 лабой должны быть пустые? Мы же после копии из мастера будем получать коды из предыдущих лаб. А так убрал код 3 лабы

Файлы с третьей лабой должны быть в мастере и в ПРе, соответственно их видно не должно быть, потому что в ПРе показывается разница между твоей веткой и мастером. Я говорила об этом в конце лекции. Удалять никакие файлы не надо, нужно правильно вливать изменения и создавать ветки)

2022-03-23 09:44 UTC, antoffee approved these changes

2022-03-23 09:44 UTC, antoffee commented on lab4/1.js
> +    let ans = [];
На будущее, если не делаешь переприсваивание, используй const

2022-03-27 16:26 UTC, merged